config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :professor_courses
  resources :professors
  resources :courses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "courses#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :professor_courses
	has_many :professors, through: :professor_courses
end

app/models/professor.rb
class Professor < ApplicationRecord
	has_many :professor_courses
	has_many :courses, through: :professor_courses
	has_many :reviews
end

app/models/professor_course.rb
class ProfessorCourse < ApplicationRecord
  belongs_to :professor
  belongs_to :course
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :professor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]
	
  def index

#  	byebug
   	@courses = Course.all

   	Rails.logger.info 'Index view accessed'
  end

  def show
  	@course = Course.find(params[:id])

  	Rails.logger.info 'Show view of Course no. '+ params[:id] +' accessed'
  end

  def new
    @course = Course.new

   	Rails.logger.info 'New view accessed'

  end

  def edit
   	Rails.logger.info 'Edit view accessed'

  end

  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_course
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:name)
    end

end

app/controllers/professor_courses_controller.rb
class ProfessorCoursesController < ApplicationController
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController

	def show
		@professor = Professor.find(params[:id])
		
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :set_review, only: %i[ show edit update destroy ]
  
  def index
   	@reviews = Review.all
   	Rails.logger.info 'Index view accessed'
  end

  def show
  	@review = Review.find(params[:id])
   	Rails.logger.info 'Show view of Review no. '+ params[:id] + ' accessed'
  end

  def new
    @review = Review.new
   	Rails.logger.info 'New view accessed'
  end

  def edit
   	Rails.logger.info 'Edit view accessed'
  end

  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to review_url(@review), notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end

	#Rails.logger.info 'Show view of persons #' + review_params[:rating] + ' accessed'

    end
  end

  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to review_url(@review), notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end

    def review_params
      params.require(:review).permit(:description, :rating, :relation, :professor_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/professor_courses_helper.rb
module ProfessorCoursesHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>">
  <p>
    <strong>Course name:</strong>
    <%= course.name %>
  </p>

</div>

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name, class:"form-control", placeholder:"Course Name" %>
  </div>
  <br>

  <div>
    <%= form.submit class:"btn btn-secondary"%>
  </div>

<% end %>

app/views/courses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Courses List</h1>

  <table class="table table-striped table-bordered table-hover">
      <thead class="table-dark">
        <tr>
          <th>Name</th>
          <th> </th>
          <th> </th>
          <th> </th>
        </tr>
      </thead>



      <div id="courses">
        <tbody>
          <% @courses.each do |course| %>
            
            <tr>
              <td>
                <%= link_to course.name, course %>
              </td>
              <td><%= link_to "Show", course %></td>
              <td><%= link_to "Edit", edit_course_path(course)  %></td>
              <td><%= button_to "Delete", course, class:"btn btn-danger", method: :delete %></td>
            </tr>

          <% end %>  

        </tbody>
        
      </div>
  </table>
  <br>

  <%= link_to 'New Course', new_course_path, class:"btn btn-secondary" %>

app/views/courses/new.html.erb
<h1>Add New course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/show.html.erb
<p style="color: green"><%= notice %></p>


<div class="jumbotron">
  <h1 class="display-4"><%= @course.name %></h1>
  
  <br>

  <h2>Professors for this course</h2>
  <div>
    <table class="table table-striped table-bordered table-hover">
      <thead class="table-dark">
        <tr>
          <th>Name</th>
          <th>Rating</th>
        </tr>
      </thead>



      <div id="professor">
        <tbody>
          <% @course.professors.each do |professor| %>
            
            <tr>
              <td>
                <%= link_to professor.name, professor %>
              </td>
              <td>
                  <% professor.reviews.average(:rating).to_i.times do  %>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                      <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                    </svg>
                  <% end %>
                    
              </td>
              

            </tr>


          <% end %>  

        </tbody>
        
      </div>
  </table>
  </div>
  <div>
    <%= link_to "Edit this course", edit_course_path(@course), class:"btn btn-secondary" %> 
    <%= link_to "Back to courses", courses_path, class:"btn btn-secondary" %>
    <br>
    <br>
    
    <%= button_to "Destroy this course", @course, class:"btn btn-danger", method: :delete %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Professor Rating System</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/professors/show.html.erb
<p style="color: green"><%= notice %></p>


<div class="jumbotron">
  <h1 class="display-4"><%= @professor.name %></h1>
  
  <br>

  <h2>Professor page</h2>
    <h3>Professor ratings: <%= @professor.reviews.average(:rating) %></h3>
    <h3>Professor ID: <%= @professor.id %></h3>
    
  <div>

  <div>
  <%= link_to 'Add reviews', new_review_path(id: @professor.id), class:"btn btn-secondary" %>
  </div>

 

</div>

app/views/reviews/_form.html.erb
<%= form_with(model: review) do |form| %>
  <% if review.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <h3>Description of review</h3>
    <%= form.text_field :description, class:"form-control", placeholder:"Description" %>
  </div>
  <br>

<br>
<br>

  <div>
    <h3>Rating from 1 to 5:</h3>

    <%= form.text_field :rating, class:"form-control", placeholder:"Enter value 1 to 5" %>
  </div>
<br>
  <div>
    <%= form.text_field :relation, class:"form-control", placeholder:"Relation" %>
  </div>
<br>
  <div>
    <% id = params[:id] %>
    <%= form.text_field :professor_id, value:id %>
  </div>

  <div>
    <%= form.submit class:"btn btn-secondary"%>
  </div>

<% end %>

app/views/reviews/new.html.erb
<h1>Add New review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Back to reviews", reviews_path %>
</div>